# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ABCMotorReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ABCMotorReact

pod 'Firebase/Core'
pod 'Firebase/Messaging', '~> 5.15.0'

  target 'ABCMotorReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  end

  target 'ABCMotorReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ABCMotorReact-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ABCMotorReact-tvOS

 
end
